# Generated by Django 5.0.2 on 2024-04-12 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('number', models.IntegerField(max_length=10)),
                ('email', models.EmailField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('last_login', models.DateTimeField(max_length=10)),
            ],
            options={
                'db_table': 'admins',
            },
        ),
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=30)),
                ('product_name', models.CharField(max_length=30)),
                ('product_price', models.IntegerField(max_length=30)),
                ('product_quantity', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'cart',
            },
        ),
        migrations.CreateModel(
            name='membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.IntegerField(max_length=10)),
                ('total_day', models.TextField(max_length=30)),
            ],
            options={
                'db_table': 'membership',
            },
        ),
        migrations.CreateModel(
            name='membership_holders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_type', models.CharField(max_length=30)),
                ('membership_price', models.IntegerField(max_length=30)),
                ('membership_total_day', models.CharField(max_length=30)),
                ('user_name', models.CharField(max_length=10)),
                ('user_email', models.EmailField(max_length=30)),
            ],
            options={
                'db_table': 'membership_holders',
            },
        ),
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('message', models.TextField(max_length=100)),
            ],
            options={
                'db_table': 'message',
            },
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.IntegerField(max_length=10)),
                ('quantity', models.TextField(max_length=30)),
                ('description', models.TextField(max_length=50)),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='trianer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('number', models.IntegerField(max_length=10)),
                ('email', models.EmailField(max_length=30)),
            ],
            options={
                'db_table': 'trianer',
            },
        ),
        migrations.CreateModel(
            name='userorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=30)),
                ('product_name', models.CharField(max_length=30)),
                ('product_price', models.IntegerField(max_length=30)),
                ('product_quantity', models.CharField(max_length=30)),
                ('user_name', models.CharField(max_length=10)),
                ('user_email', models.CharField(max_length=30)),
                ('user_address', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'userorder',
            },
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('number', models.IntegerField(max_length=10)),
                ('email', models.EmailField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('last_login', models.DateTimeField(max_length=10)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='yoga_class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yoga_trainer_name', models.CharField(max_length=30)),
                ('price', models.IntegerField(max_length=10)),
                ('total_day', models.TextField(max_length=30)),
                ('time', models.TextField(max_length=30)),
            ],
            options={
                'db_table': 'yoga_class',
            },
        ),
        migrations.CreateModel(
            name='yoga_class_member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainer_name', models.CharField(max_length=30)),
                ('class_price', models.IntegerField(max_length=30)),
                ('total_day', models.CharField(max_length=30)),
                ('class_time', models.CharField(max_length=10)),
                ('user_name', models.CharField(max_length=30)),
                ('user_email', models.EmailField(max_length=30)),
            ],
            options={
                'db_table': 'yoga_class_member',
            },
        ),
    ]
