# Generated by Django 5.0.4 on 2024-04-18 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_usercart'),
    ]

    operations = [
        migrations.CreateModel(
            name='shiping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=10)),
                ('user_email', models.EmailField(max_length=30)),
                ('user_number', models.IntegerField()),
                ('user_address', models.TextField(max_length=100)),
                ('user_city', models.TextField(max_length=30)),
                ('user_state', models.TextField(max_length=30)),
                ('user_country', models.TextField(max_length=30)),
            ],
            options={
                'db_table': 'shiping',
            },
        ),
    ]
