# Generated by Django 5.0.4 on 2024-04-18 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='hiretrainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainer_id', models.CharField(max_length=30)),
                ('trainer_name', models.CharField(max_length=30)),
                ('trainer_number', models.IntegerField(max_length=30)),
                ('trainer_email', models.EmailField(max_length=30)),
                ('total_day', models.CharField(max_length=10)),
                ('user_name', models.CharField(max_length=30)),
                ('user_email', models.EmailField(max_length=100)),
            ],
            options={
                'db_table': 'hiretrainer',
            },
        ),
    ]
